export const languages = [
    { name: 'Abkhazian', value: 'ab' },
    { name: 'Acoli', value: 'ach' },
    { name: 'Afar', value: 'aa' },
    { name: 'Afrikaans', value: 'af' },
    { name: 'Akan', value: 'ak' },
    { name: 'Albanian', value: 'sq' },
    { name: 'American Sign Language', value: 'ase' },
    { name: 'Amharic', value: 'am' },
    { name: 'Arabic', value: 'ar' },
    { name: 'Aragonese', value: 'an' },
    { name: 'Argentine Sign Language', value: 'aed' },
    { name: 'Armenian', value: 'hy' },
    { name: 'Assamese', value: 'as' },
    { name: 'Avaric', value: 'av' },
    { name: 'Avestan', value: 'ae' },
    { name: 'Aymara', value: 'ay' },
    { name: 'Azerbaijani', value: 'az' },
    { name: 'Bambara', value: 'bm' },
    { name: 'Bashkir', value: 'ba' },
    { name: 'Basque', value: 'eu' },
    { name: 'Belarusian', value: 'be' },
    { name: 'Bemba (Zambia)', value: 'bem' },
    { name: 'Bengali', value: 'bn' },
    { name: 'Berber languages', value: 'ber' },
    { name: 'Bihari languages', value: 'bh' },
    { name: 'Bislama', value: 'bi' },
    { name: 'Bosnian', value: 'bs' },
    { name: 'Brazilian Sign Language', value: 'bzs' },
    { name: 'Breton', value: 'br' },
    { name: 'Bulgarian', value: 'bg' },
    { name: 'Burmese', value: 'my' },
    { name: 'Catalan', value: 'ca' },
    { name: 'Cebuano', value: 'ceb' },
    { name: 'Celtic languages', value: 'cel' },
    { name: 'Central Bikol', value: 'bcl' },
    { name: 'Central Khmer', value: 'km' },
    { name: 'Chamorro', value: 'ch' },
    { name: 'Chechen', value: 'ce' },
    { name: 'Chilean Sign Language', value: 'csg' },
    { name: 'Chinese', value: 'zh' },
    { name: 'Church Slavic', value: 'cu' },
    { name: 'Chuukese', value: 'chk' },
    { name: 'Chuvash', value: 'cv' },
    { name: 'Colombian Sign Language', value: 'csn' },
    { name: 'Congo Swahili', value: 'swc' },
    { name: 'Cornish', value: 'kw' },
    { name: 'Corsican', value: 'co' },
    { name: 'Cree', value: 'cr' },
    { name: 'Croatian', value: 'hr' },
    { name: 'Czech', value: 'cs' },
    { name: 'Danish', value: 'da' },
    { name: 'Dari', value: 'prs' },
    { name: 'Dhivehi', value: 'dv' },
    { name: 'Dutch', value: 'nl' },
    { name: 'Dzongkha', value: 'dz' },
    { name: 'Efik', value: 'efi' },
    { name: 'English', value: 'en' },
    { name: 'Esperanto', value: 'eo' },
    { name: 'Estonian', value: 'et' },
    { name: 'Ewe', value: 'ee' },
    { name: 'Faroese', value: 'fo' },
    { name: 'Fijian', value: 'fj' },
    { name: 'Filipino', value: 'fil' },
    { name: 'Finnish', value: 'fi' },
    { name: 'Finnish Sign Language', value: 'fse' },
    { name: 'Fon', value: 'fon' },
    { name: 'French', value: 'fr' },
    { name: 'Fulah', value: 'ff' },
    { name: 'Ga', value: 'gaa' },
    { name: 'Galician', value: 'gl' },
    { name: 'Ganda', value: 'lg' },
    { name: 'Georgian', value: 'ka' },
    { name: 'German', value: 'de' },
    { name: 'Gilbertese', value: 'gil' },
    { name: 'Guarani', value: 'gn' },
    { name: 'Gujarati', value: 'gu' },
    { name: 'Gun', value: 'guw' },
    { name: 'Haitian', value: 'ht' },
    { name: 'Hausa', value: 'ha' },
    { name: 'Hawaiian', value: 'haw' },
    { name: 'Hebrew', value: 'he' },
    { name: 'Herero', value: 'hz' },
    { name: 'Hiligaynon', value: 'hil' },
    { name: 'Hindi', value: 'hi' },
    { name: 'Hiri Motu', value: 'ho' },
    { name: 'Hmong', value: 'hmn' },
    { name: 'Hmong Daw', value: 'mww' },
    { name: 'Hungarian', value: 'hu' },
    { name: 'Icelandic', value: 'is' },
    { name: 'Ido', value: 'io' },
    { name: 'Igbo', value: 'ig' },
    { name: 'Iloko', value: 'ilo' },
    { name: 'Indonesian', value: 'id' },
    { name: 'Interlingua (International Auxiliary Language Association)', value: 'ia' },
    { name: 'Interlingue', value: 'ie' },
    { name: 'Inuinnaqtun', value: 'ikt' },
    { name: 'Inuktitut', value: 'iu' },
    { name: 'Inupiaq', value: 'ik' },
    { name: 'Irish', value: 'ga' },
    { name: 'Isoko', value: 'iso' },
    { name: 'Isthmus Zapotec', value: 'zai' },
    { name: 'Italian', value: 'it' },
    { name: 'Japanese', value: 'ja' },
    { name: 'Javanese', value: 'jv' },
    { name: 'Kabyle', value: 'kab' },
    { name: 'Kalaallisut', value: 'kl' },
    { name: 'Kannada', value: 'kn' },
    { name: 'Kanuri', value: 'kr' },
    { name: 'Kaonde', value: 'kqn' },
    { name: 'Kashmiri', value: 'ks' },
    { name: 'Kazakh', value: 'kk' },
    { name: 'Kikuyu', value: 'ki' },
    { name: 'Kinyarwanda', value: 'rw' },
    { name: 'Kirghiz', value: 'ky' },
    { name: 'Klingon', value: 'tlh' },
    { name: 'Komi', value: 'kv' },
    { name: 'Kongo', value: 'kg' },
    { name: 'Korean', value: 'ko' },
    { name: 'Kuanyama', value: 'kj' },
    { name: 'Kurdish', value: 'ku' },
    { name: 'Kwangali', value: 'kwn' },
    { name: 'Lao', value: 'lo' },
    { name: 'Latin', value: 'la' },
    { name: 'Latvian', value: 'lv' },
    { name: 'Limburgan', value: 'li' },
    { name: 'Lingala', value: 'ln' },
    { name: 'Literary Chinese', value: 'lzh' },
    { name: 'Lithuanian', value: 'lt' },
    { name: 'Lozi', value: 'loz' },
    { name: 'Luba-Katanga', value: 'lu' },
    { name: 'Luba-Lulua', value: 'lua' },
    { name: 'Lunda', value: 'lun' },
    { name: 'Luo (Kenya and Tanzania)', value: 'luo' },
    { name: 'Lushai', value: 'lus' },
    { name: 'Luvale', value: 'lue' },
    { name: 'Luxembourgish', value: 'lb' },
    { name: 'Macedonian', value: 'mk' },
    { name: 'Malagasy', value: 'mg' },
    { name: 'Malay (macrolanguage)', value: 'ms' },
    { name: 'Malayalam', value: 'ml' },
    { name: 'Maltese', value: 'mt' },
    { name: 'Manx', value: 'gv' },
    { name: 'Maori', value: 'mi' },
    { name: 'Marathi', value: 'mr' },
    { name: 'Marshallese', value: 'mh' },
    { name: 'Mexican Sign Language', value: 'mfs' },
    { name: 'Modern Greek (1453-)', value: 'el' },
    { name: 'Mongolian', value: 'mn' },
    { name: 'Morisyen', value: 'mfe' },
    { name: 'Mossi', value: 'mos' },
    { name: 'Nauru', value: 'na' },
    { name: 'Navajo', value: 'nv' },
    { name: 'Ndonga', value: 'ng' },
    { name: 'Nepali (macrolanguage)', value: 'ne' },
    { name: 'Niuean', value: 'niu' },
    { name: 'North Ndebele', value: 'nd' },
    { name: 'Northern Kurdish', value: 'kmr' },
    { name: 'Northern Sami', value: 'se' },
    { name: 'Norwegian', value: 'no' },
    { name: 'Norwegian Bokmål', value: 'nb' },
    { name: 'Norwegian Nynorsk', value: 'nn' },
    { name: 'Nyaneka', value: 'nyk' },
    { name: 'Nyanja', value: 'ny' },
    { name: 'Occitan (post 1500)', value: 'oc' },
    { name: 'Ojibwa', value: 'oj' },
    { name: 'Oriya (macrolanguage)', value: 'or' },
    { name: 'Oromo', value: 'om' },
    { name: 'Ossetian', value: 'os' },
    { name: 'Pali', value: 'pi' },
    { name: 'Pangasinan', value: 'pag' },
    { name: 'Panjabi', value: 'pa' },
    { name: 'Papiamento', value: 'pap' },
    { name: 'Pedi', value: 'nso' },
    { name: 'Persian', value: 'fa' },
    { name: 'Peruvian Sign Language', value: 'prl' },
    { name: 'Pijin', value: 'pis' },
    { name: 'Pohnpeian', value: 'pon' },
    { name: 'Polish', value: 'pl' },
    { name: 'Portuguese', value: 'pt' },
    { name: 'Pushto', value: 'ps' },
    { name: 'Quechua', value: 'qu' },
    { name: 'Querétaro Otomi', value: 'otq' },
    { name: 'Romance languages', value: 'roa' },
    { name: 'Romanian', value: 'ro' },
    { name: 'Romansh', value: 'rm' },
    { name: 'Rundi', value: 'rn' },
    { name: 'Russian', value: 'ru' },
    { name: 'Ruund', value: 'rnd' },
    { name: 'Samoan', value: 'sm' },
    { name: 'San Salvador Kongo', value: 'kwy' },
    { name: 'Sango', value: 'sg' },
    { name: 'Sanskrit', value: 'sa' },
    { name: 'Sardinian', value: 'sc' },
    { name: 'Scottish Gaelic', value: 'gd' },
    { name: 'Serbian', value: 'sr' },
    { name: 'Serbo-Croatian', value: 'sh' },
    { name: 'Seselwa Creole French', value: 'crs' },
    { name: 'Shona', value: 'sn' },
    { name: 'Sichuan Yi', value: 'ii' },
    { name: 'Sindhi', value: 'sd' },
    { name: 'Sinhala', value: 'si' },
    { name: 'Slovak', value: 'sk' },
    { name: 'Slovenian', value: 'sl' },
    { name: 'Somali', value: 'so' },
    { name: 'South Ndebele', value: 'nr' },
    { name: 'Southern Sotho', value: 'st' },
    { name: 'Spanish', value: 'es' },
    { name: 'Spanish Sign Language', value: 'ssp' },
    { name: 'Sranan Tongo', value: 'srn' },
    { name: 'Sundanese', value: 'su' },
    { name: 'Swahili (macrolanguage)', value: 'sw' },
    { name: 'Swati', value: 'ss' },
    { name: 'Swedish', value: 'sv' },
    { name: 'Tagalog', value: 'tl' },
    { name: 'Tahitian', value: 'ty' },
    { name: 'Tajik', value: 'tg' },
    { name: 'Tamil', value: 'ta' },
    { name: 'Tatar', value: 'tt' },
    { name: 'Telugu', value: 'te' },
    { name: 'Tetela', value: 'tll' },
    { name: 'Tetun Dili', value: 'tdt' },
    { name: 'Thai', value: 'th' },
    { name: 'Tibetan', value: 'bo' },
    { name: 'Tigrinya', value: 'ti' },
    { name: 'Tiv', value: 'tiv' },
    { name: 'Tok Pisin', value: 'tpi' },
    { name: 'Tonga (Tonga Islands)', value: 'to' },
    { name: 'Tonga (Zambia)', value: 'toi' },
    { name: 'Tsonga', value: 'ts' },
    { name: 'Tswana', value: 'tn' },
    { name: 'Tumbuka', value: 'tum' },
    { name: 'Turkish', value: 'tr' },
    { name: 'Turkmen', value: 'tk' },
    { name: 'Tuvalu', value: 'tvl' },
    { name: 'Twi', value: 'tw' },
    { name: 'Tzotzil', value: 'tzo' },
    { name: 'Uighur', value: 'ug' },
    { name: 'Ukrainian', value: 'uk' },
    { name: 'Umbundu', value: 'umb' },
    { name: 'Upper Sorbian', value: 'hsb' },
    { name: 'Urdu', value: 'ur' },
    { name: 'Uzbek', value: 'uz' },
    { name: 'Venda', value: 've' },
    { name: 'Venezuelan Sign Language', value: 'vsl' },
    { name: 'Vietnamese', value: 'vi' },
    { name: 'Volapük', value: 'vo' },
    { name: 'Wallisian', value: 'wls' },
    { name: 'Walloon', value: 'wa' },
    { name: 'Waray (Philippines)', value: 'war' },
    { name: 'Welsh', value: 'cy' },
    { name: 'Western Frisian', value: 'fy' },
    { name: 'Wolaytta', value: 'wal' },
    { name: 'Wolof', value: 'wo' },
    { name: 'Xhosa', value: 'xh' },
    { name: 'Yapese', value: 'yap' },
    { name: 'Yiddish', value: 'yi' },
    { name: 'Yoruba', value: 'yo' },
    { name: 'Yucateco', value: 'yua' },
    { name: 'Yue Chinese', value: 'yue' },
    { name: 'Zande (individual language)', value: 'zne' },
    { name: 'Zhuang', value: 'za' },
    { name: 'Zulu', value: 'zu' },
]